# Generated by Django 5.2.8 on 2025-11-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание / Условие')),
                ('difficulty', models.CharField(choices=[('1-й уровень', '1-й уровень'), ('2-уровень', '2-уровень'), ('3-уровень', '3-уровень')], default='1-й уровень', max_length=25, verbose_name='Сложность')),
                ('max_balls', models.IntegerField(default=1, verbose_name='Максимальное количество баллов')),
                ('correct_answer', models.TextField(blank=True, verbose_name='Эталонное решение')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Заголовок')),
                ('direction', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Full Stack', 'Full Stack'), ('Data Science', 'Data Science')], default='Backend', max_length=50, verbose_name='Направление')),
                ('experience', models.CharField(choices=[('Новичок (0 лет опыта)', 'Новичок (0 лет опыта)'), ('Junior (1–3 года опыта)', 'Junior (1–3 года опыта)'), ('Middle (3–5 лет опыта)', 'Middle (3–5 лет опыта)'), ('Senior (5+ лет опыта)', 'Senior (5+ лет опыта)'), ('Team Lead / Architect (7+ лет опыта)', 'Team Lead / Architect (7+ лет опыта)')], default='Новичок (0 лет опыта)', max_length=50, verbose_name='Опыт работы')),
                ('is_remote', models.BooleanField(default=True, verbose_name='Удаленная работа')),
                ('salary_from', models.IntegerField(default=0, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(default=0, verbose_name='Зарплата до')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, help_text='Текстом, как в обычной вакансии', verbose_name='Требования')),
                ('hard_skills', models.JSONField(blank=True, default=list, help_text="Список навыков, напримео ['Python, 'Django', 'PostreSQL']", verbose_name='Хард-навыки')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('tasks', models.ManyToManyField(blank=True, help_text='Выбери задачи, которые будут предлагаться на ИИ-собеседвовании', related_name='vacancies', to='interview.task', verbose_name='Задачи для собеседования')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
