# Generated by Django 5.2.8 on 2025-11-26 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Создана'), ('active', 'В процессе'), ('finished', 'Завершена')], default='created', max_length=20, verbose_name='Статус')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Итоговый балл')),
                ('stop_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина завершения')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Закончено')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Кандидат')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='interview.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Сессия собеседования',
                'verbose_name_plural': 'Сессии собеседвоаний',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('user_answer', models.TextField(verbose_name='Ответ пользователя')),
                ('ai_reply', models.TextField(blank=True, verbose_name='Ответ ИИ / фидбек')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время вопроса')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qas', to='interview.interview', verbose_name='Сессия собеседования')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ собеседования',
                'verbose_name_plural': 'Вопросы-ответы собеседований',
                'ordering': ['-created_at'],
            },
        ),
    ]
