# Generated by Django 5.2.8 on 2025-11-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interview_interviewqa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('resume', 'В процессе резюме'), ('question', 'В процессе собеседования'), ('tasks', 'Процесс решения задач'), ('tasks_feedback', 'Процесс разбора решения задач'), ('finished', 'Завершена')], default='created', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
    ]
