# Generated by Django 5.2.8 on 2025-11-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_userresume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewqa',
            name='ai_reply',
        ),
    ]
