# Generated by Django 5.2.8 on 2025-11-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_remove_interviewqa_ai_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewqa',
            options={'ordering': ['created_at'], 'verbose_name': 'Вопрос-ответ собеседования', 'verbose_name_plural': 'Вопросы-ответы собеседований'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='total_questions',
            field=models.IntegerField(default=5, verbose_name='Количество вопросов'),
        ),
    ]
