# Generated by Django 5.2.8 on 2025-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_alter_interviewqa_options_vacancy_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='answered_questions_count',
            field=models.IntegerField(default=0, verbose_name='Количество отвеченных вопросов'),
        ),
    ]
