# Generated by Django 5.2.8 on 2025-11-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_interview_answered_questions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='answered_questions_count',
        ),
    ]
