# Generated by Django 5.2.8 on 2025-11-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_remove_interview_answered_questions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewqa',
            name='user_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ пользователя'),
        ),
    ]
