# Generated by Django 5.2.8 on 2025-11-27 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_alter_interviewqa_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='correct_answer',
        ),
        migrations.CreateModel(
            name='OutputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Выходные данные')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='interview.task')),
            ],
        ),
    ]
