# Generated by Django 5.2.8 on 2025-11-27 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_remove_task_correct_answer_outputdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_limit',
            field=models.IntegerField(default=1, max_length=3, verbose_name='Ограничение по времени'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Что поступает на вход программе', verbose_name='Входные данные')),
                ('output_data', models.TextField(help_text='Что программа ДОЛЖНА вывести', verbose_name='Ожидаемый вывод')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='interview.task', verbose_name='Задача')),
            ],
        ),
        migrations.DeleteModel(
            name='OutputData',
        ),
    ]
