# Generated by Django 5.2.8 on 2025-11-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_task_time_limit_testcase_delete_outputdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_limit',
            field=models.IntegerField(default=1, verbose_name='Ограничение по времени'),
        ),
    ]
