# Generated by Django 5.2.8 on 2025-11-27 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_alter_task_time_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-started_at'], 'verbose_name': 'Сессия собеседования', 'verbose_name_plural': 'Сессии собеседований'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('1-ый уровень', '1-ый уровень'), ('2-ой уровень', '2-ой уровень'), ('3-ий уровень', '3-ий уровень')], default='1-ый уровень', max_length=25, verbose_name='Сложность'),
        ),
        migrations.CreateModel(
            name='TaskSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(help_text='То, что написал кандидат', verbose_name='Решение кандидата (код/ответ)')),
                ('language', models.CharField(default='python', help_text='Например: python, js, c++, java и т.д.', max_length=50, verbose_name='Язык программирования')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('running', 'Выполняется'), ('done', 'Проверено'), ('error', 'Ошибка запуска / проверки')], default='pending', max_length=20, verbose_name='Статус проверки')),
                ('passed_tests', models.IntegerField(default=0, verbose_name='Пройдено тестов')),
                ('failed_tests', models.IntegerField(default=0, verbose_name='Провалено тестов')),
                ('score', models.FloatField(blank=True, help_text='Можно вычислять на основе результатов', null=True, verbose_name='Баллы за задачу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_solutions', to='interview.interview', verbose_name='Сессия собеседования')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='interview.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Решение задачи',
                'verbose_name_plural': 'Решения задач',
                'ordering': ['-created_at'],
            },
        ),
    ]
