# Generated by Django 5.2.8 on 2025-11-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Заголовок')),
                ('direction', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('fullstack', 'Full Stack'), ('datascience', 'Data Science')], default='Backend', verbose_name='Направление')),
                ('experience', models.CharField(blank=True, choices=[('no_exp', 'Новичок (0 лет опыта)'), ('junior', 'Junior (1–3 года опыта)'), ('middle', 'Middle (3–5 лет опыта)'), ('senior', 'Senior (5+ лет опыта)'), ('lead', 'Team Lead / Architect (7+ лет опыта)')], verbose_name='Опыт работы')),
                ('is_remote', models.BooleanField(default=True)),
                ('salary_from', models.IntegerField(default=0)),
                ('salary_to', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
